# Generated by Django 5.0.4 on 2024-05-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_category', '0001_initial'),
        ('books', '0002_book_video_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_category.bookcategory'),
        ),
    ]
