# Generated by Django 5.0.4 on 2024-05-09 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_book_type'),
        ('movies', '0002_remove_movie_author_remove_movie_book_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='video',
        ),
        migrations.AddField(
            model_name='book',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
