# Generated by Django 5.0.4 on 2024-05-16 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='book_text_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
