# Generated by Django 5.0.4 on 2024-05-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_text_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
